
# Etapa 1: Definir a imagem base do Node
FROM node:20-alpine

# Etapa 2: Definir o diretório de trabalho do conteiner 
WORKDIR /app

# Etapa 3: Copiar arquivos de dependencia e instalar 
COPY package*.json /.
# COPY package*.json /. mesma coisa de : COPY package.json /. COPY package-lock.json /.
RUN npm i

# Etapa 4: Copiar os restantes dos arquivos e compilar 
COPY . .
RUN npx prisma generate
RUN npm run build

# Etapa 5: Expor a porta da aplicação 
EXPOSE 3777